### DISCUSSION TITLE
How to use Custom PHP/Alpine image as running container in Azure pipeline ?

### DISCUSSION THREAD

**Discussion by abenevaut** [abenevaut/docker-kata#20] [Q&A] [answered]
https://github.com/microsoft/azure-pipelines-agent/issues/5054

Following, a pipeline example close as possible of mine:

```yaml
trigger:
  branches:
    include:
      - dev

resources:
  containers:
    - container: azsql
      image: mcr.microsoft.com/azure-sql-edge
      name: sql-server
      hostname: sql-server
      ports:
        - 1433:1433
      env:
        ACCEPT_EULA: 1
        SA_PASSWORD: yourStrong(!)Password
        MSSQL_PID: Developer

stages:

  - stage: Test
    displayName: TestStage
    jobs:
      - job: TestPHPService
        pool:
          vmImage: 'ubuntu-latest'
        container:
          image: my.azurecr.io/my/alpine-img:latest
          endpoint: 'my-service-connection'
        services:
          azsql: azsql
        steps:

          - script: |
              composer -V
              composer validate --strict
              composer install --optimize-autoloader --no-interaction --prefer-dist
            displayName: 'composer install'
            workingDirectory: $(System.DefaultWorkingDirectory)
```

The output looks like:

```
Starting: composer install
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.246.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
exec /__a/externals/node/bin/node: no such file or directory
##[error]Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'exec -i -u 1001  -w /home/vsts_azpcontainer f57d9b1f13acc1ae7fb4a68e67f1cf7883b4f535be69e03855f76e2942c6f16c /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.
Finishing: composer install
```

My image contains bash, nodejs & npm. I do not know with tool i missed.
